---
title: "Empirical Circuit Model for Output Capacitance Losses in Silicon Carbide Power Devices"
author: "Z. Tong, S. Park and J. Rivas-Davila"
date: '2019-05-27'
slug: -APEC-Coss-SiC_Tong
categories:
  - Conference
  - APEC
tags: 
  - Coss Loss
  - SiC
  - Modeling
  - Zikang Tong
  - Sanghyeon Park
doi: '10.1109/APEC.2019.8721907'
publishDate: '2019-05-27T00:00:00-01:00'
publication_types:
  - '2'
publication: "2019 IEEE Applied Power Electronics Conference and Exposition (APEC)"
publication_short: "APEC"
abstract: "In recent reports, a variety of power devices, including wide-bandgap transistors, SiC diodes, and Si superjuction MOSFETs, exhibit losses occurring from hysteretic charging and discharging of their output capacitance (C OSS for MOSFETs and C J for Schottky diodes). In many instances and soft-switching power converter applications, these losses are comparable to conduction losses, especially for HF/VHF switching frequencies. Manufacturer SPICE models and datasheets do not report these losses, and are why device power dissipation in simulation significantly contrasts with that in actual converters. However, we propose a viable empirical circuit model that incorporates these losses, with capabilities to integrate into circuit simulation tools such as SPICE. We, in addition, demonstrate the model by comparing device power dissipation in a class-E inverter and class-E rectifier between simulation and implementation."
summary: 'In recent reports, a variety of power devices, including wide-bandgap transistors, SiC diodes, and Si superjuction MOSFETs, exhibit losses occurring from hysteretic charging and discharging of their output capacitance (COSS for MOSFETs and CJ for Schottky diodes). Manufacturer SPICE models and datasheets do not report these losses, and are why device power dissipation in simulation significantly contrasts with that in actual converters. However, we propose a viable empirical circuit model that incorporates these losses, with capabilities to integrate into circuit simulation tools such as SPICE.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/8721907
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

In recent reports, a variety of power devices, including wide-bandgap transistors, SiC diodes, and Si superjuction MOSFETs, exhibit losses occurring from hysteretic charging and discharging of their output capacitance (C OSS for MOSFETs and C J for Schottky diodes). In many instances and soft-switching power converter applications, these losses are comparable to conduction losses, especially for HF/VHF switching frequencies. Manufacturer SPICE models and datasheets do not report these losses, and are why device power dissipation in simulation significantly contrasts with that in actual converters. However, we propose a viable empirical circuit model that incorporates these losses, with capabilities to integrate into circuit simulation tools such as SPICE. We, in addition, demonstrate the model by comparing device power dissipation in a class-E inverter and class-E rectifier between simulation and implementation.