---
title: "MRI Compatible DC Modulator for an Envelope Tracking Transmitter,"
author: "W. D. Braun, L. Gu, G. Scott and J. Rivas-Davila"
date: '2019-07-25'
slug: -COMPEL-MRI_Braun
categories:
  - Conference
  - COMPEL
tags: 
  - MRI
  - Envelope Tracking
  - Air Core Magnetics
  - Resonant
  - Weston Braun
  - Lei Gu
doi: '10.1109/COMPEL.2019.8769668'
publishDate: '2019-07-25T00:00:00-01:00'
publication_types:
  - '2'
publication: "2019 20th Workshop on Control and Modeling for Power Electronics (COMPEL)"
publication_short: "COMPEL"
abstract: "Typical MRI power amplifiers are characterized by the requirement for high linearity and a high peak-to-average power ratio. When implemented as a linear amplifier, such as the commonly used Class-AB architecture this leads to a low efficiency and high heat dissipation, which impacts performance and reliability. Here we present a MRI compatible DC modulator for envelope tracking applications based on a 4-phase interleaved buck converter using air core magnetics and utilizing a FPGA based digital controller. The modulator is capable of delivering 500 W into a 2.5 Ω load at an efficiency of 95.6%, has a 3 dB modulation bandwidth of 50 kHz, and has been tested with a Class-AB linear amplifier operating at 64 MHz to produce a modulated RF envelope with a peak power of 320 W. Due to the higher efficiency of envelope tracking amplifiers and the ability to mount the amplifier directly on the MRI machine itself this system has the potential to decrease both the cost and space requirements of MRI machines."
summary: 'Typical MRI power amplifiers are characterized by the requirement for high linearity and a high peak-to-average power ratio. Here we present a MRI compatible DC modulator for envelope tracking applications based on a 4-phase interleaved buck converter using air core magnetics and utilizing a FPGA based digital controller. The modulator is capable of delivering 500 W into a 2.5 Ω load at an efficiency of 95.6%, has a 3 dB modulation bandwidth of 50 kHz, and has been tested with a Class-AB linear amplifier operating at 64 MHz to produce a modulated RF envelope with a peak power of 320 W.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/8769668
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

Typical MRI power amplifiers are characterized by the requirement for high linearity and a high peak-to-average power ratio. When implemented as a linear amplifier, such as the commonly used Class-AB architecture this leads to a low efficiency and high heat dissipation, which impacts performance and reliability. Here we present a MRI compatible DC modulator for envelope tracking applications based on a 4-phase interleaved buck converter using air core magnetics and utilizing a FPGA based digital controller. The modulator is capable of delivering 500 W into a 2.5 Ω load at an efficiency of 95.6%, has a 3 dB modulation bandwidth of 50 kHz, and has been tested with a Class-AB linear amplifier operating at 64 MHz to produce a modulated RF envelope with a peak power of 320 W. Due to the higher efficiency of envelope tracking amplifiers and the ability to mount the amplifier directly on the MRI machine itself this system has the potential to decrease both the cost and space requirements of MRI machines.
