---
title: "Implementing an impedance compression network to correct misalignment in a wireless power transfer system"
author: "J. Choi and J. Rivas"
date: '2017-08-21'
slug: -COMPEL-ICN-WPT_Choi
categories:
  - Conference
  - COMPEL
tags: 
  - WPT
  - ICN
  - GaN
  - Jungwon Choi
doi: '10.1109/COMPEL.2017.8013333'
publishDate: '2017-08-21T00:00:00-01:00'
publication_types:
  - '2'
publication: "2017 IEEE 18th Workshop on Control and Modeling for Power Electronics (COMPEL)"
publication_short: "COMPEL"
abstract: "This paper presents the design and implementation of an impedance compression network (ICN) to correct distance variation or misalignment between coils in wireless power transfer (WPT) systems. Magnetic resonant coupling (MRC) coils provide high efficiency for charging mid-range WPT applications. However, a distance variation or misalignment between coils causes a coil-impedance change and significantly affects performances of WPT systems. In order to mitigate a coil-impedance variation, we propose an ICN simultaneously compressing changes in magnitude and phase of impedance. The ICN consists of a resistance compression network (RCN) and phase compression network (PCN). While the RCN effectively compresses the variation in the magnitude of impedance by using one pair consisting of an inductor and a capacitor, the PCN is designed using a Smith chart to reduce a phase variation."
summary: 'This paper presents the design and implementation of an impedance compression network (ICN) to correct distance variation or misalignment between coils in wireless power transfer (WPT) systems. Magnetic resonant coupling (MRC) coils provide high efficiency for charging mid-range WPT applications. However, a distance variation or misalignment between coils causes a coil-impedance change and significantly affects performances of WPT systems. In order to mitigate a coil-impedance variation, we propose an ICN simultaneously compressing changes in magnitude and phase of impedance. The ICN consists of a resistance compression network (RCN) and phase compression network (PCN). While the RCN effectively compresses the variation in the magnitude of impedance by using one pair consisting of an inductor and a capacitor, the PCN is designed using a Smith chart to reduce a phase variation.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/8013333
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

This paper presents the design and implementation of an impedance compression network (ICN) to correct distance variation or misalignment between coils in wireless power transfer (WPT) systems. Magnetic resonant coupling (MRC) coils provide high efficiency for charging mid-range WPT applications. However, a distance variation or misalignment between coils causes a coil-impedance change and significantly affects performances of WPT systems. In order to mitigate a coil-impedance variation, we propose an ICN simultaneously compressing changes in magnitude and phase of impedance. The ICN consists of a resistance compression network (RCN) and phase compression network (PCN). While the RCN effectively compresses the variation in the magnitude of impedance by using one pair consisting of an inductor and a capacitor, the PCN is designed using a Smith chart to reduce a phase variation.