---
title: "Reverse Recovery Testing of Small-Signal Schottky Diodes"
author: "W. Braun, E. Stolt, L. Gu and J. Rivas-Davila"
date: '2021-10-12'
slug: -ECCE-reverse_recovery_diodes-Braun
categories:
  - Conference
  - ECCE
tags: 
  - Reverse Recovery loss
  - Schottky Diodes
  - Weston Braun
  - Eric Stolt
  - Lei Gu
doi: ''
publishDate: '2021-10-12T00:00:00-01:00'
publication_types:
  - '2'
publication: "2021 IEEE Energy Conversion Congress and Exposition (ECCE)"
publication_short: "ECCE"
abstract: "Ideally, Schottky diodes have little to no reverse recovery charge due to the lack of a PN junction or associated minority carriers. However, commercial Schottky diodes incorporate a PN junction guard ring under the electrode edge. At high currents, conduction through the guard ring structure can occur, injecting minority carriers and increasing reverse recovery charge. This behavior can lead to adverse circuit effects and increased loss, especially in high frequency dc-dc converters. Moreover, this effect is little-discussed in technical literature, not captured in datasheet provided values, and not typically incorporated into manufacture provided simulation models. This paper provides an open source and low-cost diode recovery test circuit and uses it to evaluate a selection of small-signal Schottky diodes and rectifiers. In several of the diodes, we find a significant increase in the recovery charge at high currents, characteristic of the PN junction guard ring’s conduction."
summary: 'Ideally, Schottky diodes have little to no reverse recovery charge due to the lack of a PN junction or associated minority carriers. However, commercial Schottky diodes incorporate a PN junction guard ring under the electrode edge. At high currents, conduction through the guard ring structure can occur, injecting minority carriers and increasing reverse recovery charge. This behavior can lead to adverse circuit effects and increased loss, especially in high frequency dc-dc converters. Moreover, this effect is little-discussed in technical literature, not captured in datasheet provided values, and not typically incorporated into manufacture provided simulation models. This paper provides an open source and low-cost diode recovery test circuit and uses it to evaluate a selection of small-signal Schottky diodes and rectifiers. In several of the diodes, we find a significant increase in the recovery charge at high currents, characteristic of the PN junction guard ring’s conduction.'
featured: yes
links:
- icon: file-pdf
  icon_pack: fas
  name: Download author's accepted version
  url: files2download/ECCE21_paper_Weston_diode.pdf
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

Ideally, Schottky diodes have little to no reverse recovery charge due to the lack of a PN junction or associated minority carriers. However, commercial Schottky diodes incorporate a PN junction guard ring under the electrode edge. At high currents, conduction through the guard ring structure can occur, injecting minority carriers and increasing reverse recovery charge. This behavior can lead to adverse circuit effects and increased loss, especially in high frequency dc-dc converters. Moreover, this effect is little-discussed in technical literature, not captured in datasheet provided values, and not typically incorporated into manufacture provided simulation models. This paper provides an open source and low-cost diode recovery test circuit and uses it to evaluate a selection of small-signal Schottky diodes and rectifiers. In several of the diodes, we find a significant increase in the recovery charge at high currents, characteristic of the PN junction guard ring’s conduction.