---
title: "3-D Printed Air-Core Toroidal Transformer for High-Frequency Power Conversion"
author: "Z. Tong, W. D. Braun and J. M. Rivas-Davila"
date: '2019-07-25'
slug: -COMPEL-3d-aircore-transformer_Tong
categories:
  - Conference
  - COMPEL
tags: 
  - Aircore Magnetics
  - Aircore Transformer
  - Toroidal Transformer
  - 3-D Printed Magnetics
  - Zikang Tong
  - Weston Braun
doi: '10.1109/COMPEL.2019.8769674'
publishDate: '2019-07-25T00:00:00-01:00'
publication_types:
  - '2'
publication: "2019 20th Workshop on Control and Modeling for Power Electronics (COMPEL)"
publication_short: "COMPEL"
abstract: "As new applications are emerging for very-high-frequency power converters, the demand for magnetic components suitable for these frequency regimes increase. Currently, limited magnetic core materials are available above 10 MHz, therefore making air-core components the primary option. This paper presents a nested toroidal air-core transformer utilizing a 3-D printing and electroplating fabrication methodology. The first part of this work discusses design equations to achieve the target inductance matrix. Then, we provide finite-element-method (FEM) simulations in COMSOL with automation and scripting capabilities, allowing circuit designers straightforward methods in obtaining transformer parameters based on known dimensions. Lastly, this work provides experimental demonstrations of the transformer design including a 40.68 MHz 48-to-350 V resonant dc-dc converter."
summary: 'This paper presents a nested toroidal air-core transformer utilizing a 3-D printing and electroplating fabrication methodology. The first part of this work discusses design equations to achieve the target inductance matrix. Lastly, this work provides experimental demonstrations of the transformer design including a 40.68 MHz 48-to-350 V resonant dc-dc converter.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/8769674
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

As new applications are emerging for very-high-frequency power converters, the demand for magnetic components suitable for these frequency regimes increase. Currently, limited magnetic core materials are available above 10 MHz, therefore making air-core components the primary option. This paper presents a nested toroidal air-core transformer utilizing a 3-D printing and electroplating fabrication methodology. The first part of this work discusses design equations to achieve the target inductance matrix. Then, we provide finite-element-method (FEM) simulations in COMSOL with automation and scripting capabilities, allowing circuit designers straightforward methods in obtaining transformer parameters based on known dimensions. Lastly, this work provides experimental demonstrations of the transformer design including a 40.68 MHz 48-to-350 V resonant dc-dc converter.