---
title: "A compact RF power inverter with reduced EMI for a CubeSat electrothermal micro-thruster"
author: "W. Liang, X. Cui, L. Raymond, L. Gu, C. Charles, R. Boswell, J. Rivas-Davila"
date: '2017-08-21'
slug: -COMPEL-pocketrocket_Liang
categories:
  - Conference
  - COMPEL
tags: 
  - EMI
  - Cubesat
  - Sattelite Propulsion
  - RFPA
  - Wei Liang
  - Luke Raymond
  - Lei Gu
doi: '10.1109/COMPEL.2017.8013339'
publishDate: '2017-08-21T00:00:00-01:00'
publication_types:
  - '2'
publication: "2017 IEEE 18th Workshop on Control and Modeling for Power Electronics (COMPEL)"
publication_short: "COMPEL"
abstract: "This paper presents a compact RF power inverter implemented with a PCB multi-resonant input filter for driving an electrothermal plasma micro-thruster, mini Pocket Rocket 3.0 (miniPR 3.0). This miniPR 3.0 and its driving electronics are part of an investigation seeking to add micro propulsion systems to low cost CubeSats. The proposed RF power inverter and multi-resonant input filter use only air core inductors. All inductors are toroidal and formed by PCB traces and vias allowing a planar and compact design [1], [2]. The PCB structure serves as structural support to save space and volume for propulsion propellant and other payloads. Advantages of air core inductors include not being subject to saturation or variations from changing material properties of a magnetic core, as well as no Curie temperature rating. With the previous development [3] of successfully driving the miniPR 3.0 with a compact PCB RF power inverter, this paper emphasizes on addressing some of the EMI concerns. A lumped transmission line multi-resonant input filter is proposed to mitigate conductive EMI. Specifically, we present an 8 th order multi-resonant input filter design and demonstrate the converter and the filter successfully driving the miniPR 3.0."
summary: 'TThis paper presents a compact RF power inverter implemented with a PCB multi-resonant input filter for driving an electrothermal plasma micro-thruster, mini Pocket Rocket 3.0 (miniPR 3.0). This miniPR 3.0 and its driving electronics are part of an investigation seeking to add micro propulsion systems to low cost CubeSats. The proposed RF power inverter and multi-resonant input filter use only air core inductors. All inductors are toroidal and formed by PCB traces and vias allowing a planar and compact design. The PCB structure serves as structural support to save space and volume for propulsion propellant and other payloads.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/8013339
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

This paper presents a compact RF power inverter implemented with a PCB multi-resonant input filter for driving an electrothermal plasma micro-thruster, mini Pocket Rocket 3.0 (miniPR 3.0). This miniPR 3.0 and its driving electronics are part of an investigation seeking to add micro propulsion systems to low cost CubeSats. The proposed RF power inverter and multi-resonant input filter use only air core inductors. All inductors are toroidal and formed by PCB traces and vias allowing a planar and compact design [1], [2]. The PCB structure serves as structural support to save space and volume for propulsion propellant and other payloads. Advantages of air core inductors include not being subject to saturation or variations from changing material properties of a magnetic core, as well as no Curie temperature rating. With the previous development [3] of successfully driving the miniPR 3.0 with a compact PCB RF power inverter, this paper emphasizes on addressing some of the EMI concerns. A lumped transmission line multi-resonant input filter is proposed to mitigate conductive EMI. Specifically, we present an 8 th order multi-resonant input filter design and demonstrate the converter and the filter successfully driving the miniPR 3.0.