---
title: "Output capacitance losses in 600 V GaN power semiconductors with large voltage swings at high- and very-high-frequencies"
author: "G. Zulauf, W. Liang, K. Surakitbovorn and J. Rivas-Davila"
date: '2017-12-11'
slug: -WiPDA-Coss-GaN-Zulauf
categories:
  - Conference
  - APEC
tags: 
  - 
  - GaN
  - Coss Loss
  - Grayson Zulauf
  - Wei Liang
  - Kawin Surakitbovorn
doi: '10.1109/WiPDA.2017.8170572'
publishDate: '2017-12-11T00:00:00-01:00'
publication_types:
  - '2'
publication: "2017 IEEE 5th Workshop on Wide Bandgap Power Devices and Applications (WiPDA)"
publication_short: "WiPDA"
abstract: "n this paper, we construct three Class-Φ 2 resonant converters with GaN HEMT power devices, 1 kW output power, and switching frequencies of 10 MHz, 30 MHz, and 54.24 MHz. The GaN HEMTs in these converters exhibit losses, approximated thermally, that are significantly higher (up to an order of magnitude) than those predicted by simulation. To investigate, we use a Sawyer-Tower circuit to evaluate the losses in the output capacitance, C OSS , of GaN devices from each manufacturer with commercially-available power devices with voltage ratings over 600 V DS . Losses are reported from 5-35 MHz for sine, square, and Class-Φ 2 waveshapes. Steinmetz curves accurately fit the measured losses across frequency and voltage. C OSS losses for a sine wave with an amplitude equal to the device voltage rating exceed 1 μJ per cycle for two of the three devices tested here, and average C OSS power dissipation with the high-dv/dt Class-Φ 2 waveshape is tens of watts for the best performing device in our study. Higher losses are measured in the cascode device than in the enhancement-mode devices. These losses are not included in manufacturer-provided simulation models or datasheets, and, to our knowledge, were not previously reported in the literature."
summary: 'In this paper, we construct three Class-Φ 2 resonant converters with GaN HEMT power devices, 1 kW output power, and switching frequencies of 10 MHz, 30 MHz, and 54.24 MHz. The GaN HEMTs in these converters exhibit losses, approximated thermally, that are significantly higher (up to an order of magnitude) than those predicted by simulation. To investigate, we use a Sawyer-Tower circuit to evaluate the losses in the output capacitance, C OSS , of GaN devices from each manufacturer with commercially-available power devices with voltage ratings over 600 VDS .'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/8170572
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

In this paper, we construct three Class-Φ 2 resonant converters with GaN HEMT power devices, 1 kW output power, and switching frequencies of 10 MHz, 30 MHz, and 54.24 MHz. The GaN HEMTs in these converters exhibit losses, approximated thermally, that are significantly higher (up to an order of magnitude) than those predicted by simulation. To investigate, we use a Sawyer-Tower circuit to evaluate the losses in the output capacitance, C OSS , of GaN devices from each manufacturer with commercially-available power devices with voltage ratings over 600 V DS . Losses are reported from 5-35 MHz for sine, square, and Class-Φ 2 waveshapes. Steinmetz curves accurately fit the measured losses across frequency and voltage. C OSS losses for a sine wave with an amplitude equal to the device voltage rating exceed 1 μJ per cycle for two of the three devices tested here, and average C OSS power dissipation with the high-dv/dt Class-Φ 2 waveshape is tens of watts for the best performing device in our study. Higher losses are measured in the cascode device than in the enhancement-mode devices. These losses are not included in manufacturer-provided simulation models or datasheets, and, to our knowledge, were not previously reported in the literature.