---
title: "Evaluation of a 900 V SiC MOSFET in a 13.56 MHz 2 kW resonant inverter for wireless power transfer"
author: "J. Choi, D. Tsukiyama and J. Rivas"
date: '2016-09-01'
slug: -COMPEL-SiC-13M56-WPT_Choi
categories:
  - Conference
  - COMPEL
tags: 
  - WPT
  - Resonant Conversion
  - SiC
  - Jungwon Choi
doi: '10.1109/COMPEL.2016.7556746'
publishDate: '2016-09-01T00:00:00-01:00'
publication_types:
  - '2'
publication: "2016 IEEE 17th Workshop on Control and Modeling for Power Electronics (COMPEL)"
publication_short: "COMPEL"
abstract: "This paper demonstrates the performance of a 900 V silicon carbide (SiC) power MOSFET operating at 13.56 MHz in a 2 kW resonant inverter targeted for wireless power transfer (WPT) systems. Operating at multi-MHz switching frequency leads to smaller passive components and has the potential to improve power density and reduce weight for weight-sensitive applications. In addition, the advent of wide band gap (WBG) power semiconductors with higher breakdown voltages than silicon (Si) allows the design of high-power (2 kW or more) inverters even when operating at MHz frequencies. Previous work described the design and implementation of a class Φ 2 inverter using an enhancement mode gallium nitride (eGaN) FET at output power of 1.3 kW and switching at 13.56 MHz [1]. While eGaN FETs have promising electrical characteristics for high-frequency operation, SiC MOSFETs are becoming available with higher temperature ratings, higher breakdown voltages and higher avalanche ratings to operate at tens of MHz switching frequency. In this work, we study and evaluate the electrical characteristics of a 900 V, 7L D2PAK SiC MOSFET and demonstrate the design of a 2 kW single-ended resonant inverter operating at 13.56 MHz."
summary: 'This paper demonstrates the performance of a 900 V silicon carbide (SiC) power MOSFET operating at 13.56 MHz in a 2 kW resonant inverter targeted for wireless power transfer (WPT) systems. Operating at multi-MHz switching frequency leads to smaller passive components and has the potential to improve power density and reduce weight for weight-sensitive applications. In this work, we study and evaluate the electrical characteristics of a 900 V, 7L D2PAK SiC MOSFET and demonstrate the design of a 2 kW single-ended resonant inverter operating at 13.56 MHz.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/7556746
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

This paper demonstrates the performance of a 900 V silicon carbide (SiC) power MOSFET operating at 13.56 MHz in a 2 kW resonant inverter targeted for wireless power transfer (WPT) systems. Operating at multi-MHz switching frequency leads to smaller passive components and has the potential to improve power density and reduce weight for weight-sensitive applications. In addition, the advent of wide band gap (WBG) power semiconductors with higher breakdown voltages than silicon (Si) allows the design of high-power (2 kW or more) inverters even when operating at MHz frequencies. Previous work described the design and implementation of a class Φ 2 inverter using an enhancement mode gallium nitride (eGaN) FET at output power of 1.3 kW and switching at 13.56 MHz [1]. While eGaN FETs have promising electrical characteristics for high-frequency operation, SiC MOSFETs are becoming available with higher temperature ratings, higher breakdown voltages and higher avalanche ratings to operate at tens of MHz switching frequency. In this work, we study and evaluate the electrical characteristics of a 900 V, 7L D2PAK SiC MOSFET and demonstrate the design of a 2 kW single-ended resonant inverter operating at 13.56 MHz.