---
title: "High-Frequency Bidirectional Resonant Converter for High Conversion Ratio and Variable Load Operation"
author: "L. Gu, K. Surakitbovorn, G. Zulauf, S. Chakraborty and J. Rivas-Davila"
date: '2018-09-13'
slug: -COMPEL-Bidirectional_Gu
categories:
  - Conference
  - COMPEL
tags: 
  - MRI
  - Bidirectional
  - ZVS
  - RFPA
  - Lei Gu
  - Kawin Surakitbovorn
  - Grayson Zulauf
doi: '10.1109/COMPEL.2018.8459962'
publishDate: '2018-09-13T00:00:00-01:00'
publication_types:
  - '2'
publication: "2018 IEEE 19th Workshop on Control and Modeling for Power Electronics (COMPEL)"
publication_short: "COMPEL"
abstract: "Applying RF circuit design techniques to dc-dc resonant converters has enabled the switching frequency to be pushed well beyond 10 MHz, resulting in higher power densities and faster transient response. At such frequencies, it is challenging to drive all of the switches in a bidirectional converter accurately. This paper proposes a bidirectional resonant converter design in which the rectifier and the inverter switches can be driven with the same gate signal at frequencies above 10 MHz. The proposed design enables efficient operation at > 10 MHz for applications which require high conversion-ratio bidirectional power delivery. Moreover, the switches can maintain zero-voltage-switching (ZVS) over a wide load range. A 64 MHz converter single-phase converter demonstrates the operation of the circuit. An interleaving operation and a stacked architecture at the input are then proposed to further improve the performance of the proposed converter. In this paper, we demonstrate a 200 W 13.56 MHz 210 V-to-30 V bidirectional converter with a peak efficiency of 90%."
summary: 'This paper proposes a bidirectional resonant converter design in which the rectifier and the inverter switches can be driven with the same gate signal at frequencies above 10 MHz. The proposed design enables efficient operation at > 10 MHz for applications which require high conversion-ratio bidirectional power delivery. We demonstrate a 200 W 13.56 MHz 210 V-to-30 V bidirectional converter with a peak efficiency of 90%.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/8459962
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

Applying RF circuit design techniques to dc-dc resonant converters has enabled the switching frequency to be pushed well beyond 10 MHz, resulting in higher power densities and faster transient response. At such frequencies, it is challenging to drive all of the switches in a bidirectional converter accurately. This paper proposes a bidirectional resonant converter design in which the rectifier and the inverter switches can be driven with the same gate signal at frequencies above 10 MHz. The proposed design enables efficient operation at > 10 MHz for applications which require high conversion-ratio bidirectional power delivery. Moreover, the switches can maintain zero-voltage-switching (ZVS) over a wide load range. A 64 MHz converter single-phase converter demonstrates the operation of the circuit. An interleaving operation and a stacked architecture at the input are then proposed to further improve the performance of the proposed converter. In this paper, we demonstrate a 200 W 13.56 MHz 210 V-to-30 V bidirectional converter with a peak efficiency of 90%.