---
title: "On the Optimal Input Voltage of a Class-E Power Amplifier with GaN HEMTs at MHz Frequency Operation"
author: "K. Surakitbovorn, L. Gu and J. Rivas-Davila"
date: '2019-07-25'
slug: -COMPEL-classE-optimalvoltage_Surakitbovorn
categories:
  - Conference
  - COMPEL
tags: 
  - Class E
  - Optimization
  - Coss Loss
  - GaN
  - Lei Gu
  - Kawin Surakitbovorn
doi: '10.1109/COMPEL.2019.8769637'
publishDate: '2019-07-25T00:00:00-01:00'
publication_types:
  - '2'
publication: "2019 20th Workshop on Control and Modeling for Power Electronics (COMPEL)"
publication_short: "COMPEL"
abstract: "Class-E power amplifiers have regained academic interest over the past decades thanks to the introduction of new high-performance wide-bandgap semiconductor devices. While these power devices, notably GaN HEMTs, have exceptional performance at megahertz operation, they also display an additional loss component due to the C oss at this frequency. Unfortunately, the dependency of this loss term on the peak voltage is the opposite of that of the conduction loss. In this paper, we mathematically analyze the operation of a Class-E amplifier when facing with this C oss loss term. We have found that the conventional wisdom of using the highest input voltage to get the best efficiency no longer holds above a certain frequency. Furthermore, to allow this new loss term to be easily simulated, we propose a distributed loss model for the C oss loss based on a generalized Steinmetz equation (GSE). To demonstrate the applications of the proposed GSE-based C oss loss model, a design example is provided for a variable-resistance Class-E amplifier at 40.68 MHz. The experimental result on this design example shows good agreements with our analysis"
summary: 'We mathematically analyze the operation of a Class-E amplifier when facing with this Coss loss term. We have found that the conventional wisdom of using the highest input voltage to get the best efficiency no longer holds above a certain frequency. Furthermore, to allow this new loss term to be easily simulated, we propose a distributed loss model for the Coss loss based on a generalized Steinmetz equation (GSE).'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/8769637
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

Class-E power amplifiers have regained academic interest over the past decades thanks to the introduction of new high-performance wide-bandgap semiconductor devices. While these power devices, notably GaN HEMTs, have exceptional performance at megahertz operation, they also display an additional loss component due to the C oss at this frequency. Unfortunately, the dependency of this loss term on the peak voltage is the opposite of that of the conduction loss. In this paper, we mathematically analyze the operation of a Class-E amplifier when facing with this C oss loss term. We have found that the conventional wisdom of using the highest input voltage to get the best efficiency no longer holds above a certain frequency. Furthermore, to allow this new loss term to be easily simulated, we propose a distributed loss model for the C oss loss based on a generalized Steinmetz equation (GSE). To demonstrate the applications of the proposed GSE-based C oss loss model, a design example is provided for a variable-resistance Class-E amplifier at 40.68 MHz. The experimental result on this design example shows good agreements with our analysis