---
title: "Bipolar DC-DC converter topology using passive voltage reversal"
author: "Luke C. Raymond, Wei Liang, Kawin Surakitbovorn, Juan M. Rivas Davila"
date: '2021-05-04'
slug: -Patent-US10998823
categories:
  - Patent
tags: 
  - Bipolar dc-dc
  - Kawin Surakitbovorn
  - Wei Liang
  - Luke Raymond
doi: 'US10998823'
publishDate: '2021-05-04T00:00:00-01:00'
publication_types:
  - '2'
publication: "US Patent"
publication_short: "Patent"
abstract: "A resonant DC-DC converter for generating high voltage MHz bi-polar DC pulses includes a left multi-level resonant rectifier bank [100] connected to a positive electrode [104] and coupled via capacitive isolation to a left RF amplifier terminal [128]; a right multi-level resonant rectifier bank [102] connected to a negative electrode [106] and coupled via capacitive isolation to a right RF amplifier terminal [130]. Each multi-level resonant rectifier bank comprises multiple resonant rectifier stages [112-122], where each stage comprises two capacitors for capacitively isolating the stage, an output capacitor, a MOSFET switch connected to an adjacent MOSFET switch of an adjacent stage, and a gating resonant circuit connected to the MOSFET switch, whereby MOSFET switches in the banks can be passively controlled by RF signals from a left RF amplifier and a right RF amplifier."
summary: 'A resonant DC-DC converter for generating high voltage MHz bi-polar DC pulses includes a left multi-level resonant rectifier bank [100] connected to a positive electrode [104] and coupled via capacitive isolation to a left RF amplifier terminal [128]; a right multi-level resonant rectifier bank [102] connected to a negative electrode [106] and coupled via capacitive isolation to a right RF amplifier terminal [130]. Each multi-level resonant rectifier bank comprises multiple resonant rectifier stages [112-122], where each stage comprises two capacitors for capacitively isolating the stage, an output capacitor, a MOSFET switch connected to an adjacent MOSFET switch of an adjacent stage, and a gating resonant circuit connected to the MOSFET switch, whereby MOSFET switches in the banks can be passively controlled by RF signals from a left RF amplifier and a right RF amplifier.'
featured: yes
links:
- icon: google
  icon_pack: fab
  name: Publication
  url: https://patents.google.com/patent/US10998823B2/en
- icon: file-pdf
  icon_pack: fas
  name: Patent
  url: files2download/US10998823.pdf
  image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

A resonant DC-DC converter for generating high voltage MHz bi-polar DC pulses includes a left multi-level resonant rectifier bank [100] connected to a positive electrode [104] and coupled via capacitive isolation to a left RF amplifier terminal [128]; a right multi-level resonant rectifier bank [102] connected to a negative electrode [106] and coupled via capacitive isolation to a right RF amplifier terminal [130]. Each multi-level resonant rectifier bank comprises multiple resonant rectifier stages [112-122], where each stage comprises two capacitors for capacitively isolating the stage, an output capacitor, a MOSFET switch connected to an adjacent MOSFET switch of an adjacent stage, and a gating resonant circuit connected to the MOSFET switch, whereby MOSFET switches in the banks can be passively controlled by RF signals from a left RF amplifier and a right RF amplifier.