---
title: "Performance evaluation of diodes in 27.12 MHz Class-D resonant rectifiers under high voltage and high slew rate conditions"
author: "L. C. Raymond, W. Liang and J. M. Rivas"
date: '2014-08-14'
slug: -COMPEL-coss-diodes_Raymond
categories:
  - Conference
  - COMPEL
tags: 
  - Coss Loss
  - Class D Rectifier
  - Resonant rectifier
  - HV
  - Luke Raymond
  - Wei Liang
doi: '10.1109/COMPEL.2014.6877144'
publishDate: '2014-08-14T00:00:00-01:00'
publication_types:
  - '2'
publication: "2014 IEEE 15th Workshop on Control and Modeling for Power Electronics (COMPEL)"
publication_short: "COMPEL"
abstract: "This paper provides a performance review of select diodes for use in high frequency resonant rectifiers at modest power levels. Specifically, we evaluate the performance of several leading edge diodes for use in a 27.12 MHz Class-D type rectifier for output voltages from 170 V to 1000 V dc, and corresponding power levels between 8.5 W and 100 W. Previous work on resonant rectifiers at frequencies > 10 MHz [1] showed higher-than-expected losses in the diodes. These losses increased with increased output voltage and led to significant de-rating and poor utilization of the semiconductors. The authors suspect these losses are due in part to the high equation experienced by the Silicon Carbide (SiC) Schottky diodes used in that design. This paper provides an in depth comparison of select diodes to evaluate their performance for use at elevated voltages and frequencies. Further understanding of the losses involved in the design of high equation resonant rectifiers will lead to better de-rating guidelines for component selection of high frequency high voltage converters."
summary: 'This paper provides a performance review of select diodes for use in high frequency resonant rectifiers at modest power levels. Specifically, we evaluate the performance of several leading edge diodes for use in a 27.12 MHz Class-D type rectifier for output voltages from 170 V to 1000 V dc, and corresponding power levels between 8.5 W and 100 W. The authors suspect these losses are due in part to the high equation experienced by the Silicon Carbide (SiC) Schottky diodes used in that design.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/6877144
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

This paper provides a performance review of select diodes for use in high frequency resonant rectifiers at modest power levels. Specifically, we evaluate the performance of several leading edge diodes for use in a 27.12 MHz Class-D type rectifier for output voltages from 170 V to 1000 V dc, and corresponding power levels between 8.5 W and 100 W. Previous work on resonant rectifiers at frequencies > 10 MHz [1] showed higher-than-expected losses in the diodes. These losses increased with increased output voltage and led to significant de-rating and poor utilization of the semiconductors. The authors suspect these losses are due in part to the high equation experienced by the Silicon Carbide (SiC) Schottky diodes used in that design. This paper provides an in depth comparison of select diodes to evaluate their performance for use at elevated voltages and frequencies. Further understanding of the losses involved in the design of high equation resonant rectifiers will lead to better de-rating guidelines for component selection of high frequency high voltage converters.