---
title: "Design and Optimization of 6.78 MHz Wireless Power Transfer with Self-Resonant Coils"
author: "L. Gu, G. Zulauf, A. Stein, P. A. Kyaw, T. Chen and J. M. Rivas-Davila"
date: '2020-11-30'
slug: COMPEL-6M78-WPT-SelfResonantCoils_Gu
categories:
  - Conference
  - COMPEL
tags: 
  - Self Resonant Coils
  - WPT
  - High-Q resonators
  - Lei Gu
  - Grayson Zulauf
doi: '10.1109/COMPEL49091.2020.9265744'
publishDate: '2020-11-30T00:00:00-01:00'
publication_types:
  - '2'
publication: " 2020 IEEE 21st Workshop on Control and Modeling for Power Electronics (COMPEL)"
publication_short: "COMPEL"
abstract: "MHz-frequency inductive wireless power transfer holds the promise of increased power density and high- efficiency wireless power transfer. Unfortunately, due to high- frequency losses in wide-bandgap semiconductors and low-Q high-frequency coil designs, these systems are universally less efficient, on a dc-dc basis, than wireless power systems operating at conventional frequency regimes. This letter describes the design considerations for inductive wireless power transfer systems operating at 6.78 MHz. Particularly, we present the optimal compensation strategy for parallel compensated coils, which is a topic less frequently discussed in literature than the series compensated coils. With a novel high-frequency resonant amplifier topology, a high-Q self-resonant coil structure, and an optimal design strategy, we demonstrate a 6.78 MHz, 300 W wireless power transfer system that achieves 95 % dc-dc efficiency."
summary: 'MHz-frequency inductive wireless power transfer holds the promise of increased power density and high- efficiency wireless power transfer. Unfortunately, due to high- frequency losses in wide-bandgap semiconductors and low-Q high-frequency coil designs, these systems are universally less efficient, on a dc-dc basis, than wireless power systems operating at conventional frequency regimes. This letter describes the design considerations for inductive wireless power transfer systems operating at 6.78 MHz. Particularly, we present the optimal compensation strategy for parallel compensated coils, which is a topic less frequently discussed in literature than the series compensated coils. With a novel high-frequency resonant amplifier topology, a high-Q self-resonant coil structure, and an optimal design strategy, we demonstrate a 6.78 MHz, 300 W wireless power transfer system that achieves 95 % dc-dc efficiency.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/9265744
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

MHz-frequency inductive wireless power transfer holds the promise of increased power density and high- efficiency wireless power transfer. Unfortunately, due to high- frequency losses in wide-bandgap semiconductors and low-Q high-frequency coil designs, these systems are universally less efficient, on a dc-dc basis, than wireless power systems operating at conventional frequency regimes. This letter describes the design considerations for inductive wireless power transfer systems operating at 6.78 MHz. Particularly, we present the optimal compensation strategy for parallel compensated coils, which is a topic less frequently discussed in literature than the series compensated coils. With a novel high-frequency resonant amplifier topology, a high-Q self-resonant coil structure, and an optimal design strategy, we demonstrate a 6.78 MHz, 300 W wireless power transfer system that achieves 95 % dc-dc efficiency.
