---
title: "27.12 MHz isolated high voltage gain multi-level resonant DC-DC converter"
author: "L. Raymond, W. Liang, K. Surakitbovorn and J. Rivas Davila"
date: '2015-10-29'
slug: -ECCE-HV_Raymond
categories:
  - Conference
  - ECCE
tags: 
  - HV
  - Multi-level converter
  - Wei Liang
  - Luke Raymond
  - Kawin Surakitbovorn
doi: '10.1109/ECCE.2015.7310375'
publishDate: '2015-10-29T00:00:00-01:00'
publication_types:
  - '2'
publication: "2015 IEEE Energy Conversion Congress and Exposition (ECCE)"
publication_short: "ECCE"
abstract: "This paper demonstrates a high efficiency, high power density, and fast transient response dc-dc converter design capable of providing a high-voltage isolated output from a low-voltage input. Specifically, we demonstrate two 100 W, 2000 Vdc proof of concept prototype dc-dc converters operating at a switching frequency of 27.12 MHz with input voltages of 40 V and 100 V respectively. Capacitive isolation provides an efficient means of allowing for multiple rectified outputs to be combined serially without exceeding semi-conductor device limits. Further, it can provide a more efficient means of impedance matching at frequencies of 10s of MHz than traditional methods such as passive matching networks or transformers by the reduction of or elimination of those stages altogether."
summary: 'This paper demonstrates a high efficiency, high power density, and fast transient response dc-dc converter design capable of providing a high-voltage isolated output from a low-voltage input. Specifically, we demonstrate two 100 W, 2000 Vdc proof of concept prototype dc-dc converters operating at a switching frequency of 27.12 MHz with input voltages of 40 V and 100 V respectively. Capacitive isolation provides an efficient means of allowing for multiple rectified outputs to be combined serially without exceeding semi-conductor device limits. Further, it can provide a more efficient means of impedance matching at frequencies of 10s of MHz than traditional methods such as passive matching networks or transformers by the reduction of or elimination of those stages altogether.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/7310375
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

This paper demonstrates a high efficiency, high power density, and fast transient response dc-dc converter design capable of providing a high-voltage isolated output from a low-voltage input. Specifically, we demonstrate two 100 W, 2000 Vdc proof of concept prototype dc-dc converters operating at a switching frequency of 27.12 MHz with input voltages of 40 V and 100 V respectively. Capacitive isolation provides an efficient means of allowing for multiple rectified outputs to be combined serially without exceeding semi-conductor device limits. Further, it can provide a more efficient means of impedance matching at frequencies of 10s of MHz than traditional methods such as passive matching networks or transformers by the reduction of or elimination of those stages altogether.