---
title: "13.56 MHz high voltage multi-level resonant DC-DC converter"
author: "L. Raymond, W. Liang, L. Gu and J. Rivas Davila"
date: '2015-09-03'
slug: -COMPEL-HV_Raymond
categories:
  - Conference
  - COMPEL
tags: 
  - HV
  - Multi-Level
  - Luke Raymond
  - Lei Gu
  - Wei Liang
doi: '10.1109/COMPEL.2015.7236446'
publishDate: '2015-09-03T00:00:00-01:00'
publication_types:
  - '2'
publication: "2015 IEEE 16th Workshop on Control and Modeling for Power Electronics (COMPEL)"
publication_short: "COMPEL"
abstract: "This paper demonstrates a dc-dc converter that combines resonant rectifiers in a way to achieve impedance matching and significant voltage gains without the need for a high quality factor (Q) impedance matching network. Multiple stages are stacked in a way that allows for higher output voltages without suffering efficiency penalties common to traditional serial type high-voltage converter topologies such as the Crockroft-Walton Multiplier. Application of this design results in an isolated resonant dc-dc converter design that promises high efficiency, fast transient response, and high power density while providing a high-voltage isolated output from a lower-voltage input. Specifically, we demonstrate a 2000 W, 2000 Vdc output proof of concept prototype dc-dc converter operating at a switching frequency of 13.56 MHz from an input voltage of 275 Vdc. Capacitive isolation provides an efficient means of allowing for multiple rectified outputs to be combined serially without exceeding semiconductor device limits. Further, it allows for implementation of a more efficient method of impedance matching at frequencies of 10s of MHz than traditional methods such as passive matching networks or transformers by the reduction of or elimination of those stages altogether."
summary: 'This paper demonstrates a dc-dc converter that combines resonant rectifiers in a way to achieve impedance matching and significant voltage gains without the need for a high quality factor (Q) impedance matching network. Multiple stages are stacked in a way that allows for higher output voltages without suffering efficiency penalties common to traditional serial type high-voltage converter topologies such as the Crockroft-Walton Multiplier. Application of this design results in an isolated resonant dc-dc converter design that promises high efficiency, fast transient response, and high power density while providing a high-voltage isolated output from a lower-voltage input.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/7236446
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

This paper demonstrates a dc-dc converter that combines resonant rectifiers in a way to achieve impedance matching and significant voltage gains without the need for a high quality factor (Q) impedance matching network. Multiple stages are stacked in a way that allows for higher output voltages without suffering efficiency penalties common to traditional serial type high-voltage converter topologies such as the Crockroft-Walton Multiplier. Application of this design results in an isolated resonant dc-dc converter design that promises high efficiency, fast transient response, and high power density while providing a high-voltage isolated output from a lower-voltage input. Specifically, we demonstrate a 2000 W, 2000 Vdc output proof of concept prototype dc-dc converter operating at a switching frequency of 13.56 MHz from an input voltage of 275 Vdc. Capacitive isolation provides an efficient means of allowing for multiple rectified outputs to be combined serially without exceeding semiconductor device limits. Further, it allows for implementation of a more efficient method of impedance matching at frequencies of 10s of MHz than traditional methods such as passive matching networks or transformers by the reduction of or elimination of those stages altogether.