---
title: "Apparatuses and methods involving power conversion using multiple rectifier circuits"
author: "Juan Rivas-Davila, Lei Gu, Luke Raymond, Sanghyeon Park"
date: '2022-01-18'
slug: -Patent-US11228252_hv-rect
categories:
  - Patent
tags: 
  - HV
  - Rectifier
  - Lei Gu
  - Luke Raymond
  - Sanghyeon Park
doi: 'US11228252'
publishDate: '2021-01-18T00:00:00-01:00'
publication_types:
  - '2'
publication: "US Patent"
publication_short: "Patent"
abstract: "An apparatus including direct-current (DC)-alternating-current (AC) inverter circuitry, first and second circuits, and output circuitry. The DC-AC inverter circuitry inverts a DC input signal corresponding to an input voltage to an AC signal. The first circuit and second circuits respectively include inductive isolation circuits driven in response to power from the at least one AC signal, and rectifier circuits that responds to the inductive isolation circuits by outputting first and second rectified signals, where at least one of the first and second rectifier circuits characterized as being limited by a voltage breakdown rating. The output circuitry provides a DC output voltage signal and to cascade a plurality of signals, including the first and second rectified signals, to provide a voltage source that is dependent on the first and second rectified signals and greater than voltage breakdown rating."
summary: 'An apparatus including direct-current (DC)-alternating-current (AC) inverter circuitry, first and second circuits, and output circuitry. The DC-AC inverter circuitry inverts a DC input signal corresponding to an input voltage to an AC signal. The first circuit and second circuits respectively include inductive isolation circuits driven in response to power from the at least one AC signal, and rectifier circuits that responds to the inductive isolation circuits by outputting first and second rectified signals, where at least one of the first and second rectifier circuits characterized as being limited by a voltage breakdown rating. The output circuitry provides a DC output voltage signal and to cascade a plurality of signals, including the first and second rectified signals, to provide a voltage source that is dependent on the first and second rectified signals and greater than voltage breakdown rating.'
featured: yes
links:
- icon: google
  icon_pack: fab
  name: Publication
  url: https://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=1&f=G&l=50&co1=AND&d=PTXT&s1=11,228,252&OS=11,228,252&RS=11,228,252
- icon: file-pdf
  icon_pack: fas
  name: Patent
  url: files2download/US11228252B2.pdf
  image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

An apparatus including direct-current (DC)-alternating-current (AC) inverter circuitry, first and second circuits, and output circuitry. The DC-AC inverter circuitry inverts a DC input signal corresponding to an input voltage to an AC signal. The first circuit and second circuits respectively include inductive isolation circuits driven in response to power from the at least one AC signal, and rectifier circuits that responds to the inductive isolation circuits by outputting first and second rectified signals, where at least one of the first and second rectifier circuits characterized as being limited by a voltage breakdown rating. The output circuitry provides a DC output voltage signal and to cascade a plurality of signals, including the first and second rectified signals, to provide a voltage source that is dependent on the first and second rectified signals and greater than voltage breakdown rating.
