---
title: "Structurally supportive RF power inverter for a CubeSat electrothermal plasma micro-thruster with PCB inductors"
author: "W. Liang, L. Raymond, J. R. Davila, C. Charles and R. Boswell"
date: '2017-05-18'
slug: -APEC-pocketrocket_Liang
categories:
  - Conference
  - APEC
tags: 
  - Cubesat Thruster
  - PCB Converter
  - RFPA
  - Wei Liang
  - Luke Raymond
doi: '10.1109/APEC.2017.7930995'
publishDate: '2017-05-18T00:00:00-01:00'
publication_types:
  - '2'
publication: "2017 IEEE Applied Power Electronics Conference and Exposition (APEC)"
publication_short: "APEC"
abstract: "This paper presents a compact RF power inverter implemented with air core inductors for driving an electrothermal plasma micro-thruster, mini Pocket Rocket 3.0 (miniPR 3.0). This miniPR 3.0 and its driving electronics are low volume and are part of an investigation seeking to add propulsion to low cost CubeSats. The air core inductors used in the proposed RF power inverter are formed with PCB traces allowing for a planar and compact design [1], [2]. Advantages of air core inductors include not being subject to saturation or variations from changing material properties of a magnetic core. Moreover, the inductors' temperature limitations are not bounded by Curie temperature ratings. These make air core inductors suitable for operation in harsh environments like space. By incorporating the inductors within a rigid PCB, the power supply (PCB) itself can serve as a structural element for one or more of the side panels of CubeSats. This embedded multipurpose design approach minimizes the power processing unit (PPU) volumetric footprint increasing the available space for housekeeping, propellant, and/or instrument payload. In this document we propose a 13.8 MHz 14 V input 15 W RF power inverter prototype with PCB inductors and demonstrate its ability to power the miniPR 3.0. Further tests including in vacuum testing will be our future work."
summary: 'This paper presents a compact RF power inverter implemented with air core inductors for driving an electrothermal plasma micro-thruster, mini Pocket Rocket 3.0 (miniPR 3.0). This miniPR 3.0 and its driving electronics are low volume and are part of an investigation seeking to add propulsion to low cost CubeSats. The air core inductors used in the proposed RF power inverter are formed with PCB traces allowing for a planar and compact design. Advantages of air core inductors include not being subject to saturation or variations from changing material properties of a magnetic core.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/7930995
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

This paper presents a compact RF power inverter implemented with air core inductors for driving an electrothermal plasma micro-thruster, mini Pocket Rocket 3.0 (miniPR 3.0). This miniPR 3.0 and its driving electronics are low volume and are part of an investigation seeking to add propulsion to low cost CubeSats. The air core inductors used in the proposed RF power inverter are formed with PCB traces allowing for a planar and compact design [1], [2]. Advantages of air core inductors include not being subject to saturation or variations from changing material properties of a magnetic core. Moreover, the inductors' temperature limitations are not bounded by Curie temperature ratings. These make air core inductors suitable for operation in harsh environments like space. By incorporating the inductors within a rigid PCB, the power supply (PCB) itself can serve as a structural element for one or more of the side panels of CubeSats. This embedded multipurpose design approach minimizes the power processing unit (PPU) volumetric footprint increasing the available space for housekeeping, propellant, and/or instrument payload. In this document we propose a 13.8 MHz 14 V input 15 W RF power inverter prototype with PCB inductors and demonstrate its ability to power the miniPR 3.0. Further tests including in vacuum testing will be our future work.