---
title: "Low mass RF power inverter for cubesat plasma thruster using 3D printed inductors"
author: "W. Liang, L. Raymond, M. Praglin, D. Biggs, F. Righetti, M. Capelli, B. Holman and J. Rivas Davila"
date: '2016-09-01'
slug: -COMPEL-thurster_Liang
categories:
  - Conference
  - COMPEL
tags: 
  - Sattelite Thruster
  - Propulsion
  - RF
  - 3D Printed Converter
  - Aircore Inductors
  - Wei Liang
  - Luke Raymond
  - Mark Capelli
doi: '10.1109/COMPEL.2016.7556748'
publishDate: '2016-09-01T00:00:00-01:00'
publication_types:
  - '2'
publication: "2016 IEEE 17th Workshop on Control and Modeling for Power Electronics (COMPEL)"
publication_short: "COMPEL"
abstract: "This paper presents the design of a low mass RF power inverter at moderate to high power levels (e.g. tens of watts and above) for weight critical applications such as cubesat plasma thrusters. Our approach for mass reduction includes resonant switching operation at tens of MHz, and the 3D printing of light-weight scaffolds that form air core inductors after plating with a thin layer of copper. Specifically, we present a 14.2 MHz 50 W resonant DC-RF power inverter implemented with 3D printed and plated air core toroidal inductors. As a demonstration of design flexibility of the 3D printing process, these toroidal inductors are designed and implemented with optimal cross sections [1] to improve quality factors. The weight of the proposed inverter is reduced by 50% when compared to a 40 W state-of-the-art counterpart in which all the inductors were implemented within the printed circuit board (PCB). The inverter achieves 90% electrical efficiency when operated on a 50 Ω resistive load at an input voltage of 50 V. Then the inverter was implemented with a low pass matching network to drive a helicon double layer (HDL) plasma intended for a cubesat thruster application. The combined inverter and matching network outputs 40 W and achieves 86% DC input to plasma efficiency at an input voltage of 40 V."
summary: 'This paper presents the design of a low mass RF power inverter at moderate to high power levels (e.g. tens of watts and above) for weight critical applications such as cubesat plasma thrusters. Our approach for mass reduction includes resonant switching operation at tens of MHz, and the 3D printing of light-weight scaffolds that form air core inductors after plating with a thin layer of copper. Specifically, we present a 14.2 MHz 50 W resonant DC-RF power inverter implemented with 3D printed and plated air core toroidal inductors. The inverter achieves 90% electrical efficiency when operated on a 50 Ω resistive load at an input voltage of 50 V.'
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/7556748
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

This paper presents the design of a low mass RF power inverter at moderate to high power levels (e.g. tens of watts and above) for weight critical applications such as cubesat plasma thrusters. Our approach for mass reduction includes resonant switching operation at tens of MHz, and the 3D printing of light-weight scaffolds that form air core inductors after plating with a thin layer of copper. Specifically, we present a 14.2 MHz 50 W resonant DC-RF power inverter implemented with 3D printed and plated air core toroidal inductors. As a demonstration of design flexibility of the 3D printing process, these toroidal inductors are designed and implemented with optimal cross sections [1] to improve quality factors. The weight of the proposed inverter is reduced by 50% when compared to a 40 W state-of-the-art counterpart in which all the inductors were implemented within the printed circuit board (PCB). The inverter achieves 90% electrical efficiency when operated on a 50 Ω resistive load at an input voltage of 50 V. Then the inverter was implemented with a low pass matching network to drive a helicon double layer (HDL) plasma intended for a cubesat thruster application. The combined inverter and matching network outputs 40 W and achieves 86% DC input to plasma efficiency at an input voltage of 40 V.