---
title: "A physical investigation of large-signal dynamic output capacitance and energy loss in GaN-on-Si power HEMTs at high-frequency applications"
author: "J. Zhuang, G. Zulauf, J. Roig, J. D. Plummer and J. Rivas-Davila"
date: '2020-10-30'
slug: ECCE-Physical-large-signal-dynamic-output-capacitance-GaN_Zhuang
categories:
  - Conference
  - ECCE
tags: 
  - AlGaN/GaN High-electron-mobility Transistors (HEMTs)
  - Gallium Nitride (GaN)
  - Output Capacitance (Coss)
  - Power Semiconductor Devices
  - Jia Zhuang
  - Grayson Zulauf
  - James D. Plummer
doi: '10.1109/ECCE44975.2020.9235899'
publishDate: '2020-10-30T00:00:00-01:00'
publication_types:
  - '2'
publication: "2020 IEEE Energy Conversion Congress and Exposition (ECCE)"
publication_short: "ECCE"
abstract: "The origin of C oss and the energy dissipation due to output capacitance can be roughly separated into two types: resistive loss and capacitive hysteresis loss. The resistive losses are due to the resistance of GaN buffer layers and Si-substrate. These loss components can be potentially improved by re-engineering the doping concentrations in the buffer stacks and substrate layer [1] [2]. However, the capacitive hysteresis loss that is suspected to be due to trapping dynamics remains largely unexplained. This paper presents a physics view of the trapping dynamics that is related to C oss in the GaN HEMT under large-signal excitations. It is observed that under large-signal excitation, deeper traps in the buffer layers only account for a remnant portion of observed dynamic C oss losses. Instead, traps with shallow energy levels (in the range of 0.5eV above valence band) are mostly responsible for the charge imbalance and energy dissipation. By identifying dominant types of traps and relevant trap energy levels in GaN HEMT, we can gain important insights on how to optimize the device stack design for high-frequency applications."
summary: 'The origin of Coss and the energy dissipation due to output capacitance can be roughly separated into two types: resistive loss and capacitive hysteresis loss. The resistive losses are due to the resistance of GaN buffer layers and Si-substrate. These loss components can be potentially improved by re-engineering the doping concentrations in the buffer stacks and substrate layer. This paper presents a physics view of the trapping dynamics that is related to C oss in the GaN HEMT under large-signal excitations. '
featured: yes
links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://ieeexplore.ieee.org/document/9235899/
image:
  caption: ''
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
slides: ''
---

## Summary

The origin of C oss and the energy dissipation due to output capacitance can be roughly separated into two types: resistive loss and capacitive hysteresis loss. The resistive losses are due to the resistance of GaN buffer layers and Si-substrate. These loss components can be potentially improved by re-engineering the doping concentrations in the buffer stacks and substrate layer. However, the capacitive hysteresis loss that is suspected to be due to trapping dynamics remains largely unexplained. This paper presents a physics view of the trapping dynamics that is related to C oss in the GaN HEMT under large-signal excitations. It is observed that under large-signal excitation, deeper traps in the buffer layers only account for a remnant portion of observed dynamic C oss losses. Instead, traps with shallow energy levels (in the range of 0.5eV above valence band) are mostly responsible for the charge imbalance and energy dissipation. By identifying dominant types of traps and relevant trap energy levels in GaN HEMT, we can gain important insights on how to optimize the device stack design for high-frequency applications.